# app/types.py
from typing import Protocol, Any, Dict, List, Optional, AsyncGenerator

class SessionStore(Protocol):
    def get_session(self, session_id: str) -> Optional[List[Dict[str, Any]]]:
        ...
    def create_session(self, session_id: str) -> None:
        ...
    def create_message(self, session_id: str, message_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        ...
    def get_by_client_id(self, session_id: str, client_message_id: str) -> Optional[Dict[str, Any]]:
        ...
    def list_messages(self, session_id: str) -> List[Dict[str, Any]]:
        ...
    def update_message_status(self, session_id: str, message_id: str, status: str) -> None:
        ...

class InferenceService(Protocol):
    def enqueue(self, *, session_id: str, message_id: str, prompt: str, store: SessionStore) -> bool:
        ...
    def cancel(self, message_id: str) -> bool:
        ...
    def validate_token(self, token: str) -> bool:
        ...
    def queue_position(self, message_id: str) -> Optional[int]:
        ...
    def estimate_wait(self, message_id: str) -> Optional[float]:
        ...
    async def generate_tokens(self, *, prompt: str, session_id: str | None, message_id: str) -> AsyncGenerator[str, None]:
        ...
    @property
    def model_loaded(self) -> bool:
        ...
    async def shutdown(self) -> None:
        ...
